apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api-service
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: api
        image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
        ports:
        - containerPort: {{ .Values.api.service.port }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.api.service.port }}
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: {{ .Values.api.service.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
        env:
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: eventlens-configmap
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: eventlens-configmap
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: eventlens-configmap
              key: DB_PASSWORD
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: eventlens-configmap
              key: DB_PORT
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: eventlens-configmap
              key: DB_HOST
        - name: DB_MAX_CONNECTIONS
          valueFrom:
            configMapKeyRef:
              name: eventlens-configmap
              key: DB_MAX_CONNECTIONS
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: eventlens-configmap
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: eventlens-configmap
              key: REDIS_PORT
        - name: OTLP_TRACE_EXPORTER
          valueFrom:
            configMapKeyRef:
              name: eventlens-configmap
              key: OTLP_TRACE_EXPORTER
        - name: OTEL_SPAN_LINK_COUNT_LIMIT
          valueFrom:
            configMapKeyRef:
              name: eventlens-configmap
              key: OTEL_SPAN_LINK_COUNT_LIMIT
