apiVersion: v1
kind: ConfigMap
metadata:
  name: eventlens-configmap
data:
    DB_HOST: "postgres-service"
    DB_PORT: "5432"
    DB_USER: "postgres"
    DB_PASSWORD: "postgres"
    DB_NAME: "eventlens"
    DB_MAX_CONNECTIONS: "10"
    REDIS_HOST: "redis-service"
    REDIS_PORT: "6379"
    KAFKA_BROKERS: "kafka:9092"
    KAFKA_CLIENT_ID: "eventlens-app"
    KAFKA_TOPIC: "eventlens-events"
    KAFKA_CONSUMER_GROUP: "eventlens-worker-group"
    KAFKA_RETRY_TOPIC: "eventlens-events-retry"
    KAFKA_RETRY_CONSUMER_GROUP: "eventlens-retry-worker-group"
    KAFKA_TOPIC_PARTITIONS: "4"
    OTLP_TRACE_EXPORTER: "http://jaeger:4318"
    OTEL_SPAN_LINK_COUNT_LIMIT: "500"
