apiVersion: v1
kind: Service
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  selector:
    app: jaeger
  ports:
  - name: otlp-http
    port: {{ .Values.jaeger.service.otlpPort }}
    targetPort: 4318
  - name: jaeger-ui
    port: {{ .Values.jaeger.service.uiPort }}
    targetPort: 16686
