apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  replicas: {{ .Values.jaeger.replicas }}
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: "{{ .Values.jaeger.image.repository }}:{{ .Values.jaeger.image.tag }}"
        ports:
        - containerPort: 4318
          name: otlp-http
        - containerPort: 16686
          name: jaeger-ui
