apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres-service
spec:
  ports:
  - port: {{ .Values.db.service.port }}
    name: postgres-service
  clusterIP: None
  selector:
    app: postgres-service