apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.scrapeInterval }}

    scrape_configs:
      - job_name: "eventlens-api"
        static_configs:
          - targets: ["api-service:{{ .Values.api.service.port }}"]
