apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-service
spec:
  selector:
    matchLabels:
      app: redis-service # has to match .spec.template.metadata.labels
  serviceName: "redis-service"
  replicas: {{ .Values.redis.replicas }} # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: redis-service # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis-service
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        ports:
        - containerPort: {{ .Values.redis.service.port }}
          name: redis-service
        volumeMounts:
        - name: redis-volume
          mountPath: /data  # through redis.conf
  volumeClaimTemplates:
  - metadata:
      name: redis-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.redis.storage.size }}
